openapi: 3.0.3
info:
  title: Auth Service API
  description: 'API for managing auth service'
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:3002/
    description: AuthService

tags:
  - name: Authentication
    description: Login and password operations
security:
  - bearerAuth: []
paths:
  /me:
    get:
      tags: [Authentication]
      summary: Get current user data
      security:
        - bearerAuth: []
      responses:
        '200':
          description: user objects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MeResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
  /profile:
    get:
      tags: [Authentication]
      summary: Get current user profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: user profile objects
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserData'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
  /roles:
    get:
      tags: [Authentication]
      summary: List users roles
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Array of user roles objects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RoleData'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    MeResponse:
      type: object
      properties:
        app_name/roles:
          type: array
          items:
            type: string
          description: Custom claim containing assigned roles.
        iss:
          type: string
          description: Issuer identifier for the JWT.
          example: https://domain.com/
        sub:
          type: string
          description: Unique subject (user) identifier.
          example: auth0|6915a0beed*******
        aud:
          type: array
          items:
            type: string
          description: Audience values for which this token is intended.
        iat:
          type: integer
          format: int64
          description: Issued-at timestamp (Unix).
        exp:
          type: integer
          format: int64
          description: Expiration timestamp (Unix).
        scope:
          type: string
          description: OAuth scopes included in the token.
        azp:
          type: string
          description: Authorized party (client ID).
        permissions:
          type: array
          description: Permissions assigned to the user.
          items:
            type: string
    DesignationEnum:
      type: string
      enum:
        - ADMIN
        - MANAGER
        - EMPLOYEE
        - INTERN
    # Auth Schemas
    AuthLoginRequest:
      type: object
      required: [username, password]
      properties:
        username:
          type: string
        password:
          type: string
    AuthTokens:
      type: object
      properties:
        accessToken:
          type: string
        refreshToken:
          type: string
    # Roles
    RoleData:
      type: object
      properties:
        id:
          type: string
        role:
          type: string
        name:
          type: string
      required: [id, role]
    RoleDTO:
      type: object
      properties:
        role:
          type: string
        name:
          type: string
      required: [role]
    RoleUpdateDTO:
      type: object
      properties:
        role:
          type: string
        name:
          type: string
    UserData:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
          format: email
        fullName:
          type: string
        auth0_role:
          type: string
        auth0_user_id:
          type: string
        designation:
          $ref: '#/components/schemas/DesignationEnum'
        created_at:
          type: string
        updatedAt:
          type: string
      required: [id, email, username]

  examples: {}
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          example:
            code: 400
            message: Bad Request
            fields:
              - field: field1
                values:
                  - field1 cannot be empty.
                  - field1 cannot be empty.

              - field: field2
                values:
                  - field2 must be at least 8 characters long.
                  - field2 must be at least 8 characters long.
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          example:
            code: 401
            statusCode: Unauthorized

    Forbidden:
      description: Forbidden
      content:
        application/json:
          example:
            statusCode: 403
            message: Forbidden resource
            error: Forbidden
    NotFound:
      description: Not Found
      content:
        application/json:
          example:
            statusCode: 404
            message: 'Not found!'
            error: 'Not found!'
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          example:
            statusCode: 404
            message: 'Internal Server Error'
            error: 'Internal Server Error'
  parameters:
    LimitParam:
      name: limit
      in: query
      description: Number of items to return
      required: false
      schema:
        type: integer
        minimum: 0
        default: 10

    OffsetParam:
      name: offset
      in: query
      description: Number of items to skip
      required: false
      schema:
        type: integer
        minimum: 0
        default: 0
